name: Build and Deploy code

on: [push, pull_request] 

jobs:
  job1:
    runs-on: ubuntu-latest
    environment:
      name: testing    
    
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
      # Hardcode this for local testing container instead of using production secrets
      SQLALCHEMY_DATABASE_URL: "postgresql://postgres_user:postgres_test@localhost:5432/test_db"

    services:
      postgres:
        image: postgres:latest # Added version tag explicitly
        env:
          POSTGRES_USER: "postgres_user"
          POSTGRES_PASSWORD: "postgres_test" # Removed the duplicate entry
          POSTGRES_DB: "test_db"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: pulling git repo
        uses: actions/checkout@v4

      - name: Install python version 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 

      - name: update pip
        run: python -m pip install --upgrade pip

      - name: install all dependencies
        run: pip install -r requirements.txt

      - name: test with pytest
        run: |
          pip install pytest
          pytest
